'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('manifest references bundled files and only requires temporary page access',()=>{const m=JSON.parse(read('extension/manifest.json'));assert.equal(m.manifest_version,3);assert.deepEqual(m.permissions,['activeTab','scripting','storage','clipboardWrite']);assert.equal(m.host_permissions,undefined);for(const f of [m.action.default_popup,...Object.values(m.icons)])assert(fs.existsSync(path.join(root,'extension',f)));assert.equal(m.version,JSON.parse(read('package.json')).version);});
test('standalone HTML has no external script, stylesheet or remote request dependency',()=>{const html=read('docs/index.html');assert(!/<script[^>]+src\s*=/i.test(html));assert(!/<link[^>]+rel=["']stylesheet/i.test(html));assert(!/\b(fetch\s*\(|XMLHttpRequest|sendBeacon\s*\()/m.test(html));assert(html.includes('qrcode.stringToBytesFuncs'));assert(!html.includes('oss-cn-hangzhou'));});
test('bundled encoder accepts URL and Unicode and enforces capacity',()=>{const qr=require('../extension/qrcode.js');qr.stringToBytes=qr.stringToBytesFuncs['UTF-8'];for(const text of ['https://example.com','中文二维码 😀']){const q=qr(0,'M');q.addData(text);q.make();assert(q.getModuleCount()>=21);assert(q.createSvgTag().includes('<svg'));}const q=qr(0,'M');q.addData('a'.repeat(2332));assert.throws(()=>q.make());});
test('extractor resolves and deduplicates links, filters schemes, reads accessible nested roots',()=>{
 const a=(href,title)=>({getAttribute:k=>k==='href'?href:null,ownerDocument:{baseURI:'https://example.com/path/'},innerText:title,querySelector(){return null;}});
 const shadow={querySelectorAll:s=>s==='*'?[]:[a('https://shadow.example','Shadow')]},frame={querySelectorAll:s=>s==='*'?[]:[a('https://frame.example','Frame')]};
 const doc={title:'Test',querySelectorAll:s=>s==='*'?[{shadowRoot:shadow},{tagName:'IFRAME',contentDocument:frame}]:[a('../file','File'),a('../file','Duplicate'),a('javascript:alert(1)','Skip'),a('mailto:a@example.com','Mail'),a('','Blank')]};
 const s={document:doc,location:{href:'https://example.com/path/'},URL};vm.createContext(s);vm.runInContext(read('extension/extract.js'),s);const r=vm.runInContext('extractPageLinks()',s);assert.deepEqual(Array.from(r.links,x=>x.url),['https://example.com/file','mailto:a@example.com','https://shadow.example/','https://frame.example/']);
});
function popup(){
 class Element{constructor(){this.style={};this.listeners={};this.value='';this.children=[];this.textContent='';this.classList={add(){},remove(){}};}addEventListener(e,fn){this.listeners[e]=fn;}append(...e){this.children.push(...e);}replaceChildren(f){this.children=f.children;}getContext(){return {fillRect(){}};}remove(){}click(){}toBlob(fn){fn(new Blob(['test']));}}
 const els=Object.fromEntries(['source','state','canvas','placeholder','payload','png','svg','error','input','bytes','total','refresh','current','page-title','page-url','search','shown','notice','list','copy','history-search','history-list','history-status','history-tab','links-tab','links-pane','history-pane','clear-history','pick'].map(k=>[k,new Element()]));
 const tasks=new Map();let id=0;const s={qrcode:require('../extension/qrcode.js'),TextEncoder,Blob,URL,setTimeout:fn=>{tasks.set(++id,fn);return id;},clearTimeout:n=>tasks.delete(n),document:{getElementById:n=>els[n],createElement:()=>new Element(),createDocumentFragment:()=>new Element(),querySelectorAll:()=>[],body:new Element()},chrome:{runtime:{sendMessage:async()=>({ok:true,history:[],pending:null})},tabs:{query:async()=>[{id:1,url:'https://example.com',title:'Test'}]},scripting:{executeScript:async()=>[{result:{url:'https://example.com',title:'Test',links:[{url:'https://example.com/a',title:'下载'},{url:'https://example.com/b',title:'帮助'}]}}]}}};
 vm.createContext(s);vm.runInContext(read('extension/extract.js'),s);vm.runInContext(read('extension/popup.js'),s);return {els,s,flush(){const fs=[...tasks.values()];tasks.clear();fs.forEach(f=>f());}};
}
const settle=()=>new Promise(r=>setImmediate(r));
test('popup supports hover/restore, pin, search, custom input and invalid states',async()=>{const {els,flush}=popup();await settle();assert.equal(els.state.textContent,'可扫码');const link=els.list.children[0];link.listeners.mouseenter();assert.equal(els.payload.textContent,'https://example.com/a');link.listeners.mouseleave();assert.equal(els.payload.textContent,'https://example.com');link.listeners.click();link.listeners.mouseleave();assert.equal(els.payload.textContent,'https://example.com/a');els.search.value='帮助';els.search.listeners.input();assert.equal(els.list.children.length,1);els.input.value='中文测试';els.input.listeners.input();flush();assert.equal(els.payload.textContent,'中文测试');assert.equal(els.png.disabled,false);for(const value of ['', 'a'.repeat(2332)]){els.input.value=value;els.input.listeners.input();flush();assert.equal(els.png.disabled,true);}});
test('restricted-page extraction still allows custom generation',async()=>{const {els,s,flush}=popup();await settle();s.chrome.scripting.executeScript=async()=>{throw Error('blocked');};await els.refresh.listeners.click();assert(els.notice.textContent.includes('限制读取'));els.input.value='manual';els.input.listeners.input();flush();assert.equal(els.state.textContent,'可扫码');});
test('a late page response does not replace custom input',async()=>{const {els,s,flush}=popup();await settle();let done;s.chrome.scripting.executeScript=()=>new Promise(r=>{done=r;});const load=els.refresh.listeners.click();await settle();els.input.value='keep me';els.input.listeners.input();done([{result:{url:'https://late.example',title:'Late',links:[]}}]);await load;flush();assert.equal(els.payload.textContent,'keep me');});
